#! /bin/bash

if [ $# -ne 1 ]; then
    echo "usage: $0 <fileName>"
    exit 1;
fi

inFile=$1
temp=compareHC.temp

grep SP $inFile > $temp
sort -k 2 $temp > SP
awk '{gsub(";", " ", $0); printf( ": %s SP %d\n", $2, $5)}' SP > $temp.1

grep VR $inFile > $temp
sort -t \; -k 3 $temp > VR
awk -F\; '{ printf( "%s %s %s %s\n", $1, $3, $5, $6)}' VR > $temp.2
awk '{ gsub("{", " ", $0); gsub("}", " ", $0); printf( "%s VR %d %d\n", $3, $4, $5)}' $temp.2 >> $temp.1

sort -k 1 $temp.1 > $temp.3

awk -v RS=: '{ if (NF == 7) {printf( "%s SP %d VR %d %d", $1, $3, $6, $7); if( $6 != $7) printf( " [mismatch]"); if( $7 > $3) printf( " [TTL exceeded]"); if( $6 == $3) printf( " [at max distance]"); printf( "\n")}}' $temp.3 > $1.HC

rm $temp $temp.2 $temp.1 $temp.3 SP VR
